#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: http://rest-api.appgyver.com/v1/

traits:
  - securedBySteroidsApiKey:
      headers:
        steroidsApiKey:
          type: string
          example: identificationhashgoeshere
          default: 79f516a993fd2772e61ba2fcbae9eec438755978a6076453feef19e940e0f594
        steroidsAppId:
          type: integer
          example: 1234
          default: 24780

schemas:
  - commentsnews: '{"$schema":"http://json-schema.org/schema","title":"commentsnew collection","type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical commentsnew representation","properties":{"related_item_id":{"type":""},"message":{"type":""},"user_id":{"type":""},"user_name":{"type":""},"user_image_url":{"type":""},"created_at":{"type":""}},"required":[]}}'
  - commentsnew: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical commentsnew representation","properties":{"related_item_id":{"type":""},"message":{"type":""},"user_id":{"type":""},"user_name":{"type":""},"user_image_url":{"type":""},"created_at":{"type":""}},"required":[]}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>> # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName | !singularize>> # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>> # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:
      


/commentsnew:
  description: |
    {
      "resourceName": "commentsnew"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member


